@0xdbe75f90bec1f220;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("lsst::qserv");

const testClient :UInt32 = 0x54534554;

struct Test {
    helperId @0 :UInt32;
    content @1 :Text;
}
